### PR TITLE
rename `width` to `mask` to better match what it returns

### PR DESCRIPTION
**Pull request by japaric**
also add a `width` method and run rustfmt

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 69df771 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 69df7715c3f617eff8c01ee930b8fb4f0fd8120c with merge ca42d943e49896234285b667674911df882fd6c9...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/l3gd20/builds/343176782?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing ca42d943e49896234285b667674911df882fd6c9 to master...

**Pull request merged**
