### PR TITLE
add ci

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e91392c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e91392ca82bf29441cc920a11659fbb59d04522a with merge 6414fbe400a003fbd0ade5d567c4d3e5f976a99a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/l3gd20/builds/328489959?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 6414fbe400a003fbd0ade5d567c4d3e5f976a99a to master...

**Pull request merged**
